### ISSUE TITLE
Error in the description of the parameters of the INIT function for JAVA

### ISSUE THREAD

**Issue by trumdu** [BitBurst-GmbH/bitlabs-android-library#31]
Hi. I decided to upgrade to version 3.1.24

The compiler requires you to specify three parameters for initialization. According to the [documentation](https://developer.bitlabs.ai/docs/android-sdk-v3#:~:text=hold%20the%20reference%20of%20BitLabs), I see that only two parameters can be specified. Compilation with two parameters does not work.
The application has been successfully compiled with three parameters as specified in **BitLabs.class**. The application crashes with an error on startup: **java.lang.IllegalArgumentException**

![init_error](https://github.com/BitBurst-GmbH/bitlabs-android-library/assets/47075604/19311c95-b904-469c-b5e7-af7cd25849fb)

![bitlabs_class](https://github.com/BitBurst-GmbH/bitlabs-android-library/assets/47075604/32951abf-d34e-4045-a0d6-93c4056268a5)

I use Android Studio 2023.1.1.28, JAVA language. The problem also appears in the version 2022.2.1.20

**Comment by omaRaad** [comment]
@trumdu It looks like I missed to update the note in the Documentation. Although, I have updated it [here](https://developer.bitlabs.ai/docs/android-sdk-v3#:~:text=init(%3C-,Context,-%3E%2C%20%22YOUR).

But yeah now you should pass three arguments to it. The first being the Activity or Application Context.

Can you please provide logs? Otherwise, I wouldn't know what happened

**Comment by trumdu** [comment]
Thanks for the reaction. I have upgraded to 3.1.25 and I no longer have a problem. In version 3.1.25, I also couldn't repeat the problem. I pass three parameters in initialization: WebviewActivity, token, user_uuid.
